[build]
  publish = "packages/web/.next"
  command = "yarn build"

[dev]
  publish = "packages/web/.next"
  command = "yarn dev"

[functions]
  directory = "packages/functions/src"
  included_files = ["!node_modules/@swc/core-linux-x64-musl/*","!node_modules/@swc/core-linux-x64-gnu/*"]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[plugins]]
  package = "./packages/cache-netlify-plugin"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Enable this plugin to run tests on Netlify
#[[plugins]]
#  package = "netlify-plugin-cypress"
#  [plugins.inputs]
#    record = true
#    start = "yarn percy exec:start"
#    configFile = "packages/web/cypress.netlify.json"

[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = '''
    default-src 'self' *.flowise.theanswer.ai *.theanswer.ai *.sentry.io app.netlify.com *.netlify.app *.s3.amazonaws.com *.hubapi.com *.hsforms.com *.hs-scripts.com *.hsforms.net *.hscollectedforms.net *.facebook.com *.google-analytics.com *.googleoptimize.com *.googletagmanager.com *.hs-scripts.com code.jquery.com *.hsforms.net;
    connect-src 'self' *.flowise.theanswer.ai *.theanswer.ai *.sentry.io app.netlify.com *.netlify.app *.s3.amazonaws.com *.hubapi.com *.hsforms.com *.hs-scripts.com *.hsforms.net *.hscollectedforms.net *.facebook.com *.google-analytics.com *.googleoptimize.com *.googletagmanager.com *.hs-scripts.com code.jquery.com *.hsforms.net https://www.google.com https://px.ads.linkedin.com;
    style-src 'self' 'unsafe-inline' *.sentry.io *.hs-scripts.com *.hsforms.net fonts.googleapis.com;
    script-src 'unsafe-eval' 'self' 'unsafe-inline' *.flowise.theanswer.ai *.theanswer.ai *.sentry.io app.netlify.com *.netlify.app *.hs-analytics.net *.hs-banner.com *.hsadspixel.net *.hscollectedforms.net analytics.google.com *.google-analytics.com *.googletagmanager.com *.googleoptimize.com *.jquery.com *.hs-scripts.com *.hsforms.net *.googletagmanager.com *.hs-scripts.com code.jquery.com *.hsforms.net https://googleads.g.doubleclick.net https://snap.licdn.com;
    font-src 'self' *.sentry.io fonts.gstatic.com *.fontawesome.com data: *.hs-scripts.com *.hsforms.net;
    worker-src data: 'self' blob:;
    frame-src 'self' https://calendly.com https://forms.hsforms.com *.youtube.com https://td.doubleclick.net https://www.googletagmanager.com;
    img-src * data:;
    media-src * data:;
    object-src 'none';
    frame-ancestors 'self' https://app.contentful.com https://lastrev.com https://lr-live-editor.netlify.app;
  '''
  Referrer-Policy = "strict-origin-when-cross-origin"
  Strict-Transport-Security = "max-age=15768000; includeSubdomains"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
  X-XSS-Protection = "1; mode=block"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
