name: 🧪 E2E Tests - Cypress

on:
  push:
    branches: [main]
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
  lr-e2e-tests:
    uses: last-rev-llc/workflows/.github/workflows/e2e.yml@main
    with:
      provider: 'netlify'
      parallel-jobs: 5
      preview-max-timeout: 10000
      # working-directory: '.'
    secrets:
      ENVKEY: ${{ secrets.ENVKEY }}
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      SITE: ${{ secrets.SITE }}
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
